# -*- coding: utf-8 -*-

"""
APIMATICCalculatorLib

This file was automatically generated by APIMATIC BETA v2.0 on 06/28/2016
"""

class OperationTypeEnum(object):

    """Implementation of the 'Operation Type' enum.

    Possible operators are sum, subtract, multiply, divide

    Attributes:
        SUM: Represents the sum operator
        SUBTRACT: Represents the subtract operator
        MULTIPLY: Represents the multiply operator
        DIVIDE: Represents the divide operator

    """

    SUM = "SUM"

    SUBTRACT = "SUBTRACT"

    MULTIPLY = "MULTIPLY"

    DIVIDE = "DIVIDE"


    @classmethod
    def to_string(cls, val):
        """Returns the string equivalent for the Enum.

        """
        for k,v in vars(cls).iteritems():
            if v==val:
                return k

    @classmethod
    def from_string(cls, str):
        """Creates an instance of the Enum from a given string.

        """
        return getattr(cls, str.upper(), None)